server:
  port: 8081
  servlet:
    context-path: /manager
spring:
  application:
    name: managerSystem
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-bean-definition-overriding: true
  resources:
    static-locations: classpath:static

app:
  log:
    path: /home/qqz/logs/manager
    file:
      max-szie: 200MB
      max-history: 30

CHARSET: utf-8

file:
  endpoints:
    path: /home/qqz/resources/
    fileName: endpoints

